//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfNinjas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedItems
    {
        public int Id { get; set; }
        public int Ninja { get; set; }
        public int Equipment { get; set; }
    
        public virtual Equipment Equipment1 { get; set; }
        public virtual Ninja Ninja1 { get; set; }
    }
}
