//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfNinjas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LONEntities : DbContext
    {
        public LONEntities()
            : base("name=LONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Loadout> Loadout { get; set; }
        public virtual DbSet<LoadoutItems> LoadoutItems { get; set; }
        public virtual DbSet<Ninja> Ninja { get; set; }
        public virtual DbSet<PurchasedItems> PurchasedItems { get; set; }
    }
}
